import houseImage from "../assets/house-1867187_1280.jpg";
import image2 from "../assets/pexels-wdnet-101808.jpg";
import image3 from "../assets/signUp-bg.jpg";

export const houseData = [
  {
    houseId: 1223,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc_aRjilkWSxApXPz0MUS8K5N0wdAQtL4YeQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8qicfqz60nruXCFJxVl0oXnHLy7-TmHkwYA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc_aRjilkWSxApXPz0MUS8K5N0wdAQtL4YeQ&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen",
    type: "selfcon",
    price: 1200000,
    durationOfPay: "month",
    category: ["selfcon", "duplex", "flat"],
    forSale: false,
    roommateWanted: true,
  },
  {
    houseId: 123,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh-uHtcABqfKgcF7y_9jdsMvUU8bZgxWz4gw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvj7wnfjGqcq_Y1AKeQ8WoKqc6bs1iN9vHkQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEfFZjsGYOutPl5Qj1exuwcGc9luNQXj_J-A&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen, with bathroom",
    type: "selfcon",
    price: 2000000,
    durationOfPay: "6month",
    category: ["selfcon", "duplex", "flat"],
    forSale: false,
    roommateWanted: false,
  },
  {
    houseId: 12234,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlHP8do6jGS3v1aLFpebqkv8Dmj6HxLUjUSQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1aYLeDvWtFP459vgMnp3_rKd_VC3Qlh-wKQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNfYJlnWxTKo8YlF9OyrPidUl7bh68TYTpfA&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen",
    type: "selfcon",
    price: 2000000,
    durationOfPay: "year",
    category: ["selfcon", "duplex", "flat"],
    forSale: true,
    roommateWanted: false,
  },
  {
    houseId: 12243,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy04xzl5xm9Pzdpo9N2BCaNF3HKvFUirFBKA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrS-e3bTPRkeOQ3jl1b9VdEpbFAuwzN18KyQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxFcjSfmREV3ekTfnUwyoby7cRsS7GvvJU4w&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen",
    type: "selfcon",
    price: 3000000,
    durationOfPay: "month",
    category: ["selfcon", "duplex", "flat"],
    forSale: false,
    roommateWanted: true,
  },
  {
    houseId: 12243,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy04xzl5xm9Pzdpo9N2BCaNF3HKvFUirFBKA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrS-e3bTPRkeOQ3jl1b9VdEpbFAuwzN18KyQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxFcjSfmREV3ekTfnUwyoby7cRsS7GvvJU4w&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen",
    type: "selfcon",
    price: 3000000,
    durationOfPay: "month",
    category: ["selfcon", "duplex", "flat"],
    forSale: true,
    roommateWanted: false,
  },
  {
    houseId: 12243,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy04xzl5xm9Pzdpo9N2BCaNF3HKvFUirFBKA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrS-e3bTPRkeOQ3jl1b9VdEpbFAuwzN18KyQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxFcjSfmREV3ekTfnUwyoby7cRsS7GvvJU4w&s",
    ],
    address: "lekki tol gate, lagos",
    name: "2 bed room flat with kitchen",
    type: "selfcon",
    price: 3000000,
    durationOfPay: "month",
    category: ["selfcon", "duplex", "flat"],
    forSale: true,
    roommateWanted: false,
  },
];
